/**
 * @overview minimalist utils
 * @author Amir Absolutely <mr.amirka@ya.ru>
 */

const merge = require('./merge');
merge([
  require('./anyval'),
  {
    merge: merge,
    noop: require('./noop'),
    //loop: require('./loop'),
    //loopMap: require('./loop-map'),
    //range: require('./range'),
    support: require('./support'),
    aggregate: require('./aggregate'),
    breakup: require('./breakup'),
    size: require('./size'),
    getByType: require('./getByType'),
    set: require('./set'),
    get: require('./get'),
    //complement: require('./complement'),
    //destroyProvider: require('./destroy-provider'),
    eachApply: require('./eachApply'),
    eachTry: require('./eachTry'),
    cloneDepth: require('./cloneDepth'),
    //extendByPathsMap: require('./extend-by-paths-map'),
    extendDepth: require('./extendDepth'),
    flags: require('./flags'),
    flagsSet: require('./flagsSet'),
    mergeDepth: require('./mergeDepth'),
    extend: require('./extend'),
    forIn: require('./forIn'),
    forEach: require('./forEach'),
    push: require('./push'),
    pushArray: require('./pushArray'),
    withResult: require('./withResult'),
    once: require('./once'),
    delay: require('./delay'),
    immediate: require('./immediate'),
    withDefer: require('./withDefer'),
    withDelay: require('./withDelay'),
    single: require('./single'),
    //debounce: require('./debounce'),
    //throttle: require('./throttle'),
    //withReDelay: require('./with-re-delay'),
    //throttleCancelable: require('./throttle-cancelable'),
    //uniqLastApply: require('./uniq-last-apply'),
    //withoutEmpty: require('./without-empty'),
    //mapValues: require('./map-values'),
    map: require('./map'),
    reduce: require('./reduce'),
    //isCollection: require('./isCollection'),
    isEmpty: require('./isEmpty'),
    isInsign: require('./isInsign'),
    isString: require('./isString'),
    isPlainObject: require('./isPlainObject'),
    isObject: require('./isObject'),
    isArray: require('./isArray'),
    isPromise: require('./isPromise'),
    isIndex: require('./isIndex'),
    isLength: require('./isLength'),
    removeOf: require('./removeOf'),
    cssPropertiesStringifyProvider: require('./cssPropertiesStringifyProvider'),
    cssPropertiesParse: require('./cssPropertiesParse'),
    /*
    param: require('./param'),
    unparam: require('./unparam'),
    urlExtend: require('./url-extend'),
    urlParse: require('./url-parse'),
    */
    joinArrays: require('./joinArrays'),
    joinMaps: require('./joinMaps'),
    splitProvider: require('./splitProvider'),
    joinProvider: require('./joinProvider'),
    escapedSplitProvider: require('./escapedSplitProvider'),
    mapperProvider: require('./mapperProvider'),
    regexpMapperProvider: require('./regexpMapperProvider'),
    routeParseProvider: require('./routeParseProvider'),
    unslash: require('./unslash'),
    variance: require('./variance'),
    escapeQuote: require('./escapeQuote'),
    escapeRegExp: require('./escapeRegExp'),
    escapeCss: require('./escapeCss'),
    escapedBreakupProvider: require('./escapedBreakupProvider'),
    upperFirst: require('./upperFirst'),
    lowerFirst: require('./lowerFirst'),
    camelToKebabCase: require('./camelToKebabCase'),
    kebabToCamelCase: require('./kebabToCamelCase'),
    trim: require('./trim')
  }
], module.exports);
