/**
 * @overview minimalist utils
 * @author Absolutely Amir <mr.amirka@ya.ru>
 */

const merge = require('./merge');
merge([
  require('./any-val'),
  {
    merge: merge,
    noop: require('./noop'),
    loop: require('./loop'),
    loopMap: require('./loop-map'),
    range: require('./range'),
    support: require('./support'),
    aggregate: require('./aggregate'),
    breakup: require('./breakup'),
    size: require('./size'),
    getByType: require('./get-by-type'),
    set: require('./set'),
    get: require('./get'),
    complement: require('./complement'),
    destroyProvider: require('./destroy-provider'),
    eachApply: require('./each-apply'),
    eachTry: require('./each-try'),
    cloneDepth: require('./clone-depth'),
    extendByPathsMap: require('./extend-by-paths-map'),
    extendDepth: require('./extend-depth'),
    flags: require('./flags'),
    flagsSet: require('./flags-set'),
    mergeDepth: require('./merge-depth'),
    extend: require('./extend'),
    forIn: require('./for-in'),
    forEach: require('./for-each'),
    push: require('./push'),
    pushArray: require('./push-array'),
    withResult: require('./with-result'),
    once: require('./once'),
    delay: require('./delay'),
    immediate: require('./immediate'),
    withDefer: require('./with-defer'),
    withDelay: require('./with-delay'),
    single: require('./single'),
    debounce: require('./debounce'),
    throttle: require('./throttle'),
    withReDelay: require('./with-re-delay'),
    throttleCancelable: require('./throttle-cancelable'),
    uniqLastApply: require('./uniq-last-apply'),
    withoutEmpty: require('./without-empty'),
    mapValues: require('./map-values'),
    map: require('./map'),
    reduce: require('./reduce'),
    isCollection: require('./is-collection'),
    isEmpty: require('./is-empty'),
    isInsign: require('./is-insign'),
    isString: require('./is-string'),
    isPlainObject: require('./is-plain-object'),
    isObject: require('./is-object'),
    isArray: require('./is-array'),
    isPromise: require('./is-promise'),
    isIndex: require('./is-index'),
    isLength: require('./is-length'),
    removeOf: require('./remove-of'),
    cssPropertiesStringifyProvider: require('./css-properties-stringify-provider'),
    cssPropertiesParse: require('./css-properties-parse'),
    /*
    param: require('./param'),
    unparam: require('./unparam'),
    urlExtend: require('./url-extend'),
    urlParse: require('./url-parse'),
    */
    joinArrays: require('./join-arrays'),
    joinMaps: require('./join-maps'),
    splitProvider: require('./split-provider'),
    joinProvider: require('./join-provider'),
    escapedSplitProvider: require('./escaped-split-provider'),
    mapperProvider: require('./mapper-provider'),
    regexpMapperProvider: require('./regexp-mapper-provider'),
    routeParseProvider: require('./route-parse-provider'),
    unslash: require('./unslash'),
    variance: require('./variance'),
    escapeQuote: require('./escape-quote'),
    escapeRegExp: require('./escape-reg-exp'),
    escapeCss: require('./escape-css'),
    escapedBreakupProvider: require('./escaped-breakup-provider'),
    upperFirst: require('./upper-first'),
    lowerFirst: require('./lower-first'),
    camelToKebabCase: require('./camel-to-kebab-case'),
    kebabToCamelCase: require('./kebab-to-camel-case')
  }
], module.exports);
